############################ Default configuration #########################
baseURL = "https://kcretro.kierancollins.co.uk/"
title = "KC RETRO REVIEW SITE | Retro Gaming Review and Game Walthroughs"
# theme
theme = "northendlab"
languageCode = "en-gb"
paginate = "10"
# post excerpt
summaryLength = "10"
# disable language
disableLanguages = [""] # desable language from here

[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[markup.goldmark.renderer]
    unsafe = true
[markup.highlight]
      codeFences = true
      guessSyntax = true
      hl_Lines = ""
      lineNoStart = 1
      lineNos = false
      lineNumbersInTable = false
      tabWidth = 4
      noClasses = false

######################### Default Parameters ###########################
[params]
# logo
logo = "images/navlogo.png"
logoWidth = 248
logoHeight = 50
# favicon
favicon = "images/favicon.png"
# meta data
author = "Kieran Collins"
description = "Having Fun with Retro"
# homepage main section
mainSections = ["posts"]
# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io
# copyright
copyright = ""
rssLimit = 20
# search *** true or false (if Search is disable Menu will align in Right) ***
search = true

header_search_layout = "expanded" # "expanded" or "popupable"
# Menu align *** "left", "right" or "center" (if Search is disable Menu will align in Right) ***
menu_align = "center"
# Blog-details page sidebar
sidebar = "right" # Sidebar value ("left", "right" or false)

# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "" # example: G-XXXXXXXXXX

code_copy_button = true # Turn on/off the code-copy-button for code-fields

######################## Site Variables #########################
[params.variables]
# Color Variables
primary_color = "#47c4f1"
secondary_color = "#9AC4F8"
text_color = "#666666"
text_color_dark = "#222222"
body_color = "#fff"
border_color = "#ACB9C4"
black = "#000"
white = "#fff"
light = "#F8F8F8"

# font variable
# Give your font name from google font. add font weight using ":wght@" and separate by ";"
# example: "Work Sans:wght@400;500;600"
primary_font = "PT Sans:wght@400;700"
secondary_font = ""
icon_font = "Font Awesome 5 Free"
   
######################## sidebar widgets #########################
[params.widgets]
sidebar = ["toc", "categories", "tags"]
# available widget : search,about-me,authors,categories,tags,recent-post,social,promotion,subscription

# preloader
[params.preloader]
enable = false
preloader = "" # use png, jpg, svg or gif format

# Google Ads
[params.googlead]
enable = false

# cookies
[params.cookies]
enable = false
expire_days = 2

########################## Plugings ######################################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.min.css"
[[params.plugins.css]]
link = "css/custom-nav.css"


# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js"
attributes = "crossorigin='anonymous' defer='defer' data-search-pseudo-elements"


############################## Social Site ##########################
[[params.social]]
icon = "fab fa-github" # Fontawesome icon pack https://fontawesome.com/icons
link = "https://github.com/KC-OU"

# - [] need to do indeed username and url

 
# [[params.social]]
#icon = "fab fa-linkedin" # Fontawesome icon pack https://fontawesome.com/icons
#link = "https://www.linkedin.com/in/ctitus/"
####################### Banner #######################################

######################## About Me Widget ###############################
[about_me]
title = "Kieran Collins"
bio = ""

[[params.social_profile]]
icon = "fab fa-github" # Fontawesome icon pack https://fontawesome.com/icons
link = "https://github.com/kc-ou"
#[[params.social_profile]]
#icon = "fab fa-linkedin" # Fontawesome icon pack https://fontawesome.com/icons
#link = "https://www.linkedin.com/in/ctitus/"

######################## call to action ###############################
[params.cta]
enable = false
image = "images/hugo-muscot.svg"
title = "Get the best hugo templates"
description = "Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus."

[params.cta.button]
enable = false
label = "Visit Here"
link = "https://gethugothemes.com/shop/"

############################# English - Main Menu ########################
[[menu.main]]
weight = 1
url = "/"
name = "Home"

[[menu.main]]
weight = 2
url = "#"
name = "Reviews"
hasChildren = true

[[menu.main]]
    name = "gameboy"
    url = "/categories/gameboy"
    parent = "Reviews"

[[menu.main]]
    name = "gameboy Advance"
    url = "/categories/gameboyadvance"
    parent = "Reviews"

[[menu.main]]
    name = "gameboy Color"
    url = "/categories/gameboycolor"
    parent = "Reviews"

[[menu.main]]
    name = "gamecube"
    url = "/categories/gamecube"
    parent = "Reviews"

[[menu.main]]
    name = "Nintendo 3DS"
    url = "/categories/Nintendo3DS"
    parent = "Reviews"

[[menu.main]]
    name = "Nintendo 64"
    url = "/categories/nintendo64"
    parent = "Reviews"

[[menu.main]]
    name = "Nintendo DS"
    url = "/categories/nintendods"
    parent = "Reviews"

[[menu.main]]
    name = "Nintendo Wii"
    url = "/categories/nintendowii"
    parent = "Reviews"

[[menu.main]]
    name = "Nintendo Wii U"
    url = "/categories/nintendowiiu"
    parent = "Reviews"

[[menu.main]]
    name = "Playstation 1"
    url = "/categories/playstation1"
    parent = "Reviews"

[[menu.main]]
    name = "Playstation 2"
    url = "/categories/playstation2"
    parent = "Reviews"

[[menu.main]]
    name = "Playstation 3"
    url = "/categories/playstation3"
    parent = "Reviews"

[[menu.main]]
    name = "Playstation Portable"
    url = "/categories/playstationportable"
    parent = "Reviews"
#############################  Walkthoughts ########################
[[menu.main]]
weight = 3
url = "#"
name= "Walkthroughs"
hasChildren = true
  
[[menu.main]]
    name = "GB Walkthroughs"
    url = "/categories/gameboy-walkthroughs"
    parent = "Walkthroughs"
[[menu.main]]
    name = "GBA-Walthroughs"
    url = "/categories/gameboyadvance-walkthroughs"
    parent = "Walkthroughs"
[[menu.main]]
    name = "GBC-Walkthroughs"
    url = "/categories/Gameboy-Color-walkthroughs"
    parent = "Walkthroughs"
[[menu.main]]
    name = "GC - Walthroughs"
    url = "/categories/gamecube-walkthroughs"
    parent = "Walkthroughs"
[[menu.main]]
    name = "N3DS Walkthroughs"
    url = "/categories/Nintendo3DS-walkthroughs"
    parent = "Walkthroughs"
[[menu.main]]
    name = "N64 - Walkthroughs"
    url = "/categories/nintendo64-walkthroughs"
    parent = "Walkthroughs"
[[menu.main]]
    name = "NDS-Walkthroughs"
    url = "/categories/nintendo-ds-walkthroughs"
    parent = "Walkthroughs"
[[menu.main]]
    name = "Wii-Walkthroughs"
    url = "/categories/nintendo-wii-walkthroughs"
    parent = "Walkthroughs"
[[menu.main]]
    name = "WiiU-Walkthroughs"
    url = "/categories/nintendo-wiiu-walkthroughs"
    parent = "Walkthroughs"
[[menu.main]]
    name = "PS1-Walkthroughs"
    url = "/categories/playstation-1-walkthroughs"
    parent = "Walthroughs"
[[menu.main]]
    name = "PS2-Walkthroughs"
    url = "/categories/playstation-2-walkthroughs"
    parent = "Walkthroughs"
[[menu.main]]
    name = "PS3-Walkthroughs"
    url = "/categories/playstation-3-walkthroughs"
    parent = "Walkthroughs"
[[menu.main]]
    name = "PSP-Walkthroughs"
    url = "/categories/playstation-portable-walkthroughs"
    parent = "Walkthroughs"
########################## Links ########################
[[menu.main]]
    weight = 4
    url = "https://retroachievements.org/user/KieranCollins"
    name = "Retro A"

[[menu.main]]
    weight = 5
    url = "https://www.mobygames.com/"
    name = "Moby G"
